// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fedorova_t.v_kt_41_22.Database;

#nullable disable

namespace fedorova_t.v_kt_41_22.Migrations
{
    [DbContext(typeof(TeacherDbContext))]
    [Migration("20250427100744_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.AcademicDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("degree_Id")
                        .HasComment("Id уч. степени");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Name")
                        .HasComment("Название уч. степени");

                    b.HasKey("Id")
                        .HasName("pl_AcademicDegree_degree_id");

                    b.ToTable("AcademicDegree", (string)null);
                });

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Department_Id")
                        .HasComment("Id факультета");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FoundedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Founded_Date")
                        .HasComment("Дата основания факультета");

                    b.Property<int?>("HeadId")
                        .HasColumnType("int")
                        .HasColumnName("Head_Id")
                        .HasComment("Id зав. кафедры");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("Name")
                        .HasComment("Название факультета");

                    b.HasKey("Id")
                        .HasName("pl_Departments_department_id");

                    b.HasIndex("HeadId")
                        .IsUnique()
                        .HasFilter("[Head_Id] IS NOT NULL");

                    b.HasIndex(new[] { "HeadId" }, "idx_Departments_fk_f_head_id");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Discipline_Id")
                        .HasComment("Id дисциплины");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Discipline_Name")
                        .HasComment("Название дисциплины");

                    b.HasKey("Id")
                        .HasName("pl_Disciplines_discipline_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_Disciplines_name");

                    b.ToTable("Disciplines", (string)null);
                });

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Load", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Load_Id")
                        .HasComment("Id нагрузки");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("Discipline_Id")
                        .HasComment("Id дисциплины");

                    b.Property<int>("Hours")
                        .HasColumnType("int")
                        .HasColumnName("Hours")
                        .HasComment("Количество часов нагрузки");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("Teacher_Id")
                        .HasComment("Id преподавателя");

                    b.HasKey("Id")
                        .HasName("pl_Loads_load_id");

                    b.HasIndex(new[] { "DisciplineId" }, "idx_Loads_fk_f_discipline_id");

                    b.HasIndex(new[] { "TeacherId" }, "idx_Loads_fk_f_teacher_id");

                    b.ToTable("Loads", (string)null);
                });

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Position_Id")
                        .HasComment("Id должности");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Position_Name")
                        .HasComment("Название должности");

                    b.HasKey("Id")
                        .HasName("pl_Positions_position_id");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Teacher_Id")
                        .HasComment("Id преподавателя");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DegreeId")
                        .HasColumnType("int")
                        .HasColumnName("Degree_Id")
                        .HasComment("Id ученой степени");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("Department_Id")
                        .HasComment("Id кафедры");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("First_Name")
                        .HasComment("Имя преподавателя");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("Last_Name")
                        .HasComment("Фамилия преподавателя");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("Position_Id")
                        .HasComment("Id занимаемой должности");

                    b.HasKey("Id")
                        .HasName("pl_Teachers_teacher_id");

                    b.HasIndex("PositionId");

                    b.HasIndex(new[] { "DegreeId" }, "idx_Teachers_fk_f_degree_id");

                    b.HasIndex(new[] { "DepartmentId" }, "idx_Teachers_fk_f_department_id");

                    b.HasIndex(new[] { "DegreeId" }, "idx_Teachers_fk_f_position_id");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Department", b =>
                {
                    b.HasOne("fedorova_t.v_kt_41_22.Models.Teacher", "Head")
                        .WithOne()
                        .HasForeignKey("fedorova_t.v_kt_41_22.Models.Department", "HeadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_f_head_id");

                    b.Navigation("Head");
                });

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Load", b =>
                {
                    b.HasOne("fedorova_t.v_kt_41_22.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_discipline_id");

                    b.HasOne("fedorova_t.v_kt_41_22.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_teacher_id");

                    b.Navigation("Discipline");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Teacher", b =>
                {
                    b.HasOne("fedorova_t.v_kt_41_22.Models.AcademicDegree", "AcademicDegree")
                        .WithMany()
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_degree_id");

                    b.HasOne("fedorova_t.v_kt_41_22.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_department_id");

                    b.HasOne("fedorova_t.v_kt_41_22.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_position_id");

                    b.Navigation("AcademicDegree");

                    b.Navigation("Department");

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
