' <auto-generated />
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Migrations
Imports fedorova_t.v_kt_41_22.Database
Namespace fedorova_t.v_kt_41_22.Migrations
    <DbContext(GetType(TeacherDbContext))>
    <Migration("20250325135232_CreateDatabase")>
    Partial Class CreateDatabase
        ''' <inheritdoc/>
        Protected Overrides Sub BuildTargetModel(modelBuilder As ModelBuilder)
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16").HasAnnotation("Relational:MaxIdentifierLength", 128)

            modelBuilder.UseIdentityColumns()

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.AcademicDegree", Sub(b)
                                                                                   b.Property(Of Integer)("Id").ValueGeneratedOnAdd().HasColumnType("int")

                                                                                   b.[Property](Of Integer)("Id").UseIdentityColumn()

                                                                                   b.Property(Of String)("Title").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)")

                                                                                   b.HasKey("Id")

                                                                                   b.ToTable("AcademicDegrees", CStr(Nothing))
                                                                               End Sub)

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Department", Sub(b)
                                                                               b.Property(Of Integer)("Id").ValueGeneratedOnAdd().HasColumnType("int")

                                                                               b.[Property](Of Integer)("Id").UseIdentityColumn()

                                                                               b.[Property](Of Integer?)("HeadId").HasColumnType("int")

                                                                               b.Property(Of String)("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)")

                                                                               b.HasKey("Id")

                                                                               b.HasIndex("HeadId").IsUnique().HasFilter("[HeadId] IS NOT NULL")

                                                                               b.ToTable("Departments", CStr(Nothing))
                                                                           End Sub)

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Discipline", Sub(b)
                                                                               b.Property(Of Integer)("Id").ValueGeneratedOnAdd().HasColumnType("int")

                                                                               b.[Property](Of Integer)("Id").UseIdentityColumn()

                                                                               b.Property(Of String)("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)")

                                                                               b.HasKey("Id")

                                                                               b.ToTable("Disciplines", CStr(Nothing))
                                                                           End Sub)

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Load", Sub(b)
                                                                         b.Property(Of Integer)("Id").ValueGeneratedOnAdd().HasColumnType("int")

                                                                         b.[Property](Of Integer)("Id").UseIdentityColumn()

                                                                         b.[Property](Of Integer)("DisciplineId").HasColumnType("int")

                                                                         b.[Property](Of Integer)("Hours").HasColumnType("int")

                                                                         b.[Property](Of Integer)("TeacherId").HasColumnType("int")

                                                                         b.HasKey("Id")

                                                                         b.HasIndex("DisciplineId")

                                                                         b.HasIndex("TeacherId")

                                                                         b.ToTable("Loads", CStr(Nothing))
                                                                     End Sub)

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Position", Sub(b)
                                                                             b.Property(Of Integer)("Id").ValueGeneratedOnAdd().HasColumnType("int")

                                                                             b.[Property](Of Integer)("Id").UseIdentityColumn()

                                                                             b.Property(Of String)("Title").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)")

                                                                             b.HasKey("Id")

                                                                             b.ToTable("Positions", CStr(Nothing))
                                                                         End Sub)

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Teacher", Sub(b)
                                                                            b.Property(Of Integer)("Id").ValueGeneratedOnAdd().HasColumnType("int")

                                                                            b.[Property](Of Integer)("Id").UseIdentityColumn()

                                                                            b.[Property](Of Integer?)("AcademicDegreeId").HasColumnType("int")

                                                                            b.[Property](Of Integer?)("DepartmentId").HasColumnType("int")

                                                                            b.Property(Of String)("FirstName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)")

                                                                            b.Property(Of String)("LastName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)")

                                                                            b.[Property](Of Integer?)("PositionId").HasColumnType("int")

                                                                            b.HasKey("Id")

                                                                            b.HasIndex("AcademicDegreeId")

                                                                            b.HasIndex("DepartmentId")

                                                                            b.HasIndex("PositionId")

                                                                            b.ToTable("Teachers", CStr(Nothing))
                                                                        End Sub)

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Department", Sub(b)
                                                                               b.HasOne("fedorova_t.v_kt_41_22.Models.Teacher", "Head").WithOne("ManagedDepartment").HasForeignKey("fedorova_t.v_kt_41_22.Models.Department", "HeadId").OnDelete(DeleteBehavior.Restrict)

                                                                               b.Navigation("Head")
                                                                           End Sub)

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Load", Sub(b)
                                                                         b.HasOne("fedorova_t.v_kt_41_22.Models.Discipline", "Discipline").WithMany("Loads").HasForeignKey("DisciplineId").OnDelete(DeleteBehavior.Restrict).IsRequired()

                                                                         b.HasOne("fedorova_t.v_kt_41_22.Models.Teacher", "Teacher").WithMany("Loads").HasForeignKey("TeacherId").OnDelete(DeleteBehavior.Cascade).IsRequired()

                                                                         b.Navigation("Discipline")

                                                                         b.Navigation("Teacher")
                                                                     End Sub)

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Teacher", Sub(b)
                                                                            b.HasOne("fedorova_t.v_kt_41_22.Models.AcademicDegree", "AcademicDegree").WithMany("Teachers").HasForeignKey("AcademicDegreeId").OnDelete(DeleteBehavior.Restrict)

                                                                            b.HasOne("fedorova_t.v_kt_41_22.Models.Department", "Department").WithMany("Teachers").HasForeignKey("DepartmentId").OnDelete(DeleteBehavior.Cascade)

                                                                            b.HasOne("fedorova_t.v_kt_41_22.Models.Position", "Position").WithMany("Teachers").HasForeignKey("PositionId").OnDelete(DeleteBehavior.Restrict)

                                                                            b.Navigation("AcademicDegree")

                                                                            b.Navigation("Department")

                                                                            b.Navigation("Position")
                                                                        End Sub)

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.AcademicDegree", Sub(b) b.Navigation("Teachers"))

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Department", Sub(b) b.Navigation("Teachers"))

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Discipline", Sub(b) b.Navigation("Loads"))

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Position", Sub(b) b.Navigation("Teachers"))

            modelBuilder.Entity("fedorova_t.v_kt_41_22.Models.Teacher", Sub(b)
                                                                            b.Navigation("Loads")

                                                                            b.Navigation("ManagedDepartment")
                                                                        End Sub)
        End Sub
    End Class
End Namespace
